### ISSUE TITLE
[RFC] The issue of oneToMany relation

### ISSUE THREAD

**Issue by churow** [phpMv/ubiquity-dev#3]
## Background

There are two models, Job and Emp.
A Job has serveral roles for each Emp to take.
The roles are writer, translator, proofreader, etc.
These roles are made as properties of Job model (not as another Role model).
Each of the roles has foreign key relation to Emp.

## Issues

"Ubiquity all-models" makes Job and Emp like this:

Job
```
	/**
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Emp","name"=>"job_proofreader","nullable"=>false)
	**/
	private $emp;

	/**
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Emp","name"=>"job_translator","nullable"=>false)
	**/
	private $emp1;

	/**
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Emp","name"=>"job_writer","nullable"=>false)
	**/
	private $emp2;
```

Emp
```
	/**
	 * @oneToMany("mappedBy"=>"emp","className"=>"models\\Job")
	**/
	private $jobs;

	/**
	 * @oneToMany("mappedBy"=>"emp","className"=>"models\\Job")
	**/
	private $jobs1;

	/**
	 * @oneToMany("mappedBy"=>"emp","className"=>"models\\Job")
	**/
	private $jobs2;
```

1. The names of the properties, and also the names of the getter and the setter are hard to tell which one is which.

2. The sequence numbers that make each property unique might change if new properties are added to Job and "Ubiquity all-models" again, because it is ordered _alphabetically_.

3. The bigger issue is that the annotation of oneToMany relation has the same "mappedBy" values for each $jobs's,
so that when they are used thru "$included" parameters like the code below, only the first Emp property, job_proofreader is used in LEFT JOIN statement for all job, job1, and job2, which is done in Ubiquity\orm\traits\DAORelationsPrepareTrait's prepareOneToMany() and Ubiquity\orm\traits\OrmUtilsRelationsTrait's getUJoinSQL().
```
$emps = DAO::uGetAll(Emp::class, "some conditions", ['job', 'job1', 'job2']);
```

## My suggestion

It would be better if each of the properties have semantic name like $emp_job_writer, $emp_job_translator, $emp_job_proofreader for Job model and $jobs_job_writer, $jobs_job_translator, $jobs_job_proofreader for Emp model.

## My modification

app/config/config.php
```
	"database"=>array(
			// ...
			"useFkSuffix"=>true,
			),
```

vendor/phpmv/ubiquity-dev/src/orm/creator/ModelCreator.php
```
// ...
abstract class ModelsCreator:
	protected function createRelations():
		// ...
		$fkTable = $fk["TABLE_NAME"];
		$fkSuffix = (array_key_exists('useFkSuffix', $this->config) && $this->config['useFkSuffix'] && $fk["COLUMN_NAME"] != $key) ? "_" . $fk["COLUMN_NAME"] : "";
		$this->classes[$table]->addOneToMany(\lcfirst($fkTable) . "s" . $fkSuffix, \lcfirst($table) . $fkSuffix, $this->classes[$fkTable]->getName());
		$this->classes[$fkTable]->addManyToOne($field . $fkSuffix, \lcfirst($fk["COLUMN_NAME"]), $class->getName());
		// ...
```
The useFkSuffix config is used not to spoil existing models unexpectedly.
The $key is exempted becuase it is too much to have such a suffix for ordinary only-one-foreign-key case.

**Comment by jcheron** [comment]
Thank you @churow 
It is a very good issue, complete and clear.

I was also not satisfied with the automatic numbering used to generate unique member names.
So I agree that we need to find a much more semantic naming solution.

I would be in favor of not using the proposed configuration which concerns the production part while the generation of classes is done in development:
```php
"database"=>array(
			// ...
			"useFkSuffix"=>true,
			),
```

It would perhaps be preferable that in case of non-unique member name on the generation of relations, the generator uses by default the name of the foreign key and as a last resort the automatic numbering.
In this case, no further configuration is needed.

If the Job table is structured in this way:
### The job Table
```sql
CREATE TABLE `job` (
  `id` int(11) NOT NULL,
  `name` varchar(65) DEFAULT NULL,
  `proofreaderId` int(11) NOT NULL,
  `translatorId` int(11) NOT NULL,
  `writerId` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

### Members In the class Job
should be:
```php
	/**
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Emp","name"=>"proofreaderId","nullable"=>false)
	 */
	private $proofReader;

	/**
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Emp","name"=>"translatorId","nullable"=>false)
	 */
	private $translator;

	/**
	 * @manyToOne
	 * @joinColumn("className"=>"models\\Emp","name"=>"writerId","nullable"=>false)
	 */
	private $writer;
```

### Naming convention
So I think we should establish a naming convention for foreign keys in case of multiple relationships with the same table, and communicate it in the documentation to the users.

The generator will have to take into account and use this convention.

I propose :
- foreign key name: `{pkName}xxx` or  `xxx{pkName}`
- member name: `xxx`
